name: "Lint Addon"
on:
  push:
    branches:
      - master
    paths:
      - "src/**"
  pull_request:
    paths:
      - "src/**"
jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext lint"
        uses: kewisch/action-web-ext@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cmd: lint
          source: src
          channel: unlisted
